### ISSUE TITLE
CMake library target

### ISSUE THREAD

**Issue by JosiahWI** [tuxalin/THST#10]
Thank you for the nice library. I'm trying it out in a PR to the open source project Minetest, because libspatialindex isn't as convenient to extend for line intersection.

I've had to write my own Find script for your library; it would be a nice feature if you provided an interface library target yourselves. If this is something you'd appreciate as a contribution, I would be happy to PR a basic CMakeLists.txt to create an INTERFACE target with the appropriate include directory attached.

**Comment by tuxalin** [comment]
Glad it was useful, yes, I didn't consider that but it's a nice idea so please feel free to create a PR.
