### ISSUE TITLE
Uninitialized variable warning

### ISSUE THREAD

**Issue by JosiahWI** [tuxalin/THST#12]
I get a warning about `best` possibly being uninitialized on RTree.h line 866 in the function `QUAL_TREE::pickBranch`. I looked at the code, and it asserts the node count, so I don't think the variable will really be used uninitialized; however, it would be nice to have the warning fixed.

OS: Debian Bullseye
Compiler: GCC 10

**Comment by tuxalin** [comment]
I get it too, it shouldn't happened as mentioned, but I wanted to avoid any unnecessary initialization.
Made a fix for it, should have done it like that from the start.
