### ISSUE TITLE
Removing ValueType in QuadTree

### ISSUE THREAD

**Issue by CyberPlaton** [tuxalin/THST#17]
Greetings,

I fail to see how I can manage dynamic objects (which change their position, rotation etc).

My current workaround is that on each frame I clear the Quad Tree and reinsert all entities in the scene (which is the obvious bottleneck).

Preferably I would do the reinsertion only for those ValueType objects, that have actually moved etc., like a dirty flag type of thing, so I my question is: is it possible to add a remove/update function for a ValueType object? Or are there better approaches I do not see?

Best regards

**Comment by CyberPlaton** [comment]
Considered - yes, but this seems more like a workaround to be honest.

**Comment by tuxalin** [comment]
That's a good point with having a dynamic version, in some cases it might be faster, but you would have to profile.
In this case it would also help to have a remove function, I'll add one.

**Comment by tuxalin** [comment]
Added a remove function for the quad tree.
