### ISSUE TITLE
Add catch framework and unit tests

### ISSUE THREAD

**Issue by tuxalin** [tuxalin/THST#3]

**Comment by onqtam** [comment]
[doctest](https://github.com/onqtam/doctest) is another option :D

**Comment by JosiahWI** [comment]
I'm interested in doing this. I've also looked into doctest and I really liked what I saw.

**Comment by tuxalin** [comment]
@JosiahWI  Nice! Indeed, doctest is a great option and would be really useful.

**Comment by tuxalin** [comment]
Updated all tests to use doctest.
